name: iStampit Timestamp
description: "Stamp build artifacts with OpenTimestamps"
inputs:
  paths:
    description: "Glob(s) of files to stamp"
    required: true
  upgrade:
    description: "Upgrade proofs if calendars can complete them"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install --upgrade pip opentimestamps-client
      shell: bash
    - run: |
        python - <<'PY'
        import glob, os, subprocess, json
        paths = os.environ['INPUT_PATHS']
        files = [f for g in paths.split(',') for f in glob.glob(g.strip(), recursive=True)]
        receipts = []
        for f in files:
            subprocess.check_call(['ots','stamp',f])
            r = f + '.ots'
            if os.environ.get('INPUT_UPGRADE','false').lower() == 'true':
                subprocess.call(['ots','upgrade', r])
            receipts.append(r)
        print(json.dumps({'receipts': receipts}))
        PY
      shell: bash
