permissions:
  contents: read
name: Example iStampit Action
on: [push]
jobs:
  stamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create dummy file
        run: echo "hello" > test.txt
      - name: Run local action
        id: stamp
        uses: ./
        with:
          paths: "test.txt"
          upgrade: "true"
      - name: Verify receipt exists
        run: test -f test.txt.ots && echo "Receipt OK" || (echo "Missing receipt" && exit 1)
      - name: Show receipts output
        run: |
          echo "Receipts: ${{ steps.stamp.outputs.receipts }}"
